# conda env create --file environment.yml
# mamba env create --file environment.yml
name: penguins_exploratorio
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib==3.6.0
  - numpy==1.23.4
  - pandas==1.5.1
  - pip
  - plotly
  - pyprojroot
  - python=3.9
  - seaborn==0.12.1
  - empiricaldist==0.6.7
  - statsmodels==0.13.5
  - scikit-learn==1.1.2
  - pyjanitor==0.23.1
  - session-info
pip:
  - palmerpenguins==0.1.4
